model:
  target: models.policy.Policy
  params:
    lr: 1e-5
    norm_loss_wight: 0.05
    ckpt_path: logs/policy/2025-01-11T13-33-07/checkpoints/checkpoints.ckpt
    dino_model: "dinov2_vitg14"
    use_local: True
    transformer_config:
      target: models.attention.models.Transformer
      params:
        out_dim: 128
        d_model_en: 384
        d_model_de: 384
        d_inner: 128
        n_layers: 4
        n_head: 8
        d_k: 64
        d_v: 64
        dropout: 0.0
        n_position: 5000
        scale_emb: True
        

trainer:
  gpus: 1
  monitor: "train/total_loss"
  accumulate_grad_batches: 8
  every_n_train_steps: 500
  dataset: 
    target: data.vs_dataset.PklDataset
    params:
      data_root: "/home/cyx/project/policy/sample/data/"
  dataloader:
    batch_size: 8
    num_workers: 4
  logger: 
    target: pytorch_lightning.loggers.TensorBoardLogger
    params:
      save_dir: "logs/"

